# Generated by Django 5.0.3 on 2024-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15, null=True)),
                ('pass1', models.CharField(max_length=15, null=True)),
                ('pass2', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
